package org.zhenchao.passport.oauth.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zhenchao.passport.oauth.model.Scope;
import org.zhenchao.passport.oauth.model.ScopeExample;

public interface ScopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scope
     *
     * @mbg.generated Wed Dec 28 16:41:47 CST 2016
     */
    long countByExample(ScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scope
     *
     * @mbg.generated Wed Dec 28 16:41:47 CST 2016
     */
    int deleteByExample(ScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scope
     *
     * @mbg.generated Wed Dec 28 16:41:47 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scope
     *
     * @mbg.generated Wed Dec 28 16:41:47 CST 2016
     */
    int insert(Scope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scope
     *
     * @mbg.generated Wed Dec 28 16:41:47 CST 2016
     */
    int insertSelective(Scope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scope
     *
     * @mbg.generated Wed Dec 28 16:41:47 CST 2016
     */
    List<Scope> selectByExample(ScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scope
     *
     * @mbg.generated Wed Dec 28 16:41:47 CST 2016
     */
    Scope selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scope
     *
     * @mbg.generated Wed Dec 28 16:41:47 CST 2016
     */
    int updateByExampleSelective(@Param("record") Scope record, @Param("example") ScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scope
     *
     * @mbg.generated Wed Dec 28 16:41:47 CST 2016
     */
    int updateByExample(@Param("record") Scope record, @Param("example") ScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scope
     *
     * @mbg.generated Wed Dec 28 16:41:47 CST 2016
     */
    int updateByPrimaryKeySelective(Scope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scope
     *
     * @mbg.generated Wed Dec 28 16:41:47 CST 2016
     */
    int updateByPrimaryKey(Scope record);
}